<?xml version="1.0" encoding="utf-8"?><Database Name="EVAC290920" Class="PMSDataClassesDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=3.7.30.86,1480\SQLEXPRESS;Initial Catalog=EVAC290920;Persist Security Info=True;User ID=sa" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="EVAC290920ConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Master_Hierarchy" Member="Master_Hierarchies">
    <Type Name="Master_Hierarchy">
      <Column Name="Hierarchy_ID" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Hierarchy_Name" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="Hierarchy_Description" Type="System.String" DbType="VarChar(1200)" CanBeNull="true" />
      <Column Name="CREATED_DATE" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CREATED_BY" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.v_employee_details" Member="v_employee_details">
    <Type Name="v_employee_detail">
      <Column Name="cnt_internalId" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="cnt_UCC" Type="System.String" DbType="VarChar(80)" CanBeNull="true" />
      <Column Name="Name" Type="System.String" DbType="VarChar(252)" CanBeNull="true" />
      <Column Name="deg_designation" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="job_responsibility" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.PMS_OPRHIERARCHY" Member="PMS_OPRHIERARCHies">
    <Type Name="PMS_OPRHIERARCHY">
      <Column Name="ID" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="OID" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="NAME" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
      <Column Name="DESCRIPTION" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
      <Column Name="OPERHEAD" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="PARENT_ID" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="Hierarchy_ID" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.V_WBS" Member="V_WBs">
    <Type Name="V_WB">
      <Column Name="WBS_ID" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="WBS_Code" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="WBS_Name" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
      <Column Name="WBS_HierarchyId" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="WBS_Branch" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="WBS_StartDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="WBS_EndTime" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="WBS_Duration" Type="System.Decimal" DbType="Decimal(18,4)" CanBeNull="true" />
      <Column Name="WBS_Description" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="WBS_Workunit" Type="System.String" DbType="VarChar(8)" CanBeNull="true" />
      <Column Name="Proj_Name" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="H_Name" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="CREATED" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="MODIFIED" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="LAST_MODIFIED" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="branch_description" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="Effort" Type="System.String" DbType="VarChar(59)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.v_PMS_TimeSheet" Member="v_PMS_TimeSheets">
    <Type Name="v_PMS_TimeSheet">
      <Column Name="TimeSheet_ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="TimeSheet_Date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="TimeSheet_DurationID" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="Time_Duration" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="TimeSheet_TypeID" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="Type_Name" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="TimeSheet_ProjectID" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="Proj_Name" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="TimeSheet_ProjectTaskID" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="ProjectTask_Name" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
      <Column Name="TimeSheet_RollID" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="ROLE_NAME" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="TimeSheet_Description" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="TimeSheet_ExternalComments" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="CreatedBy" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Create_Date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="UpdatedBy" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="branch_id" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="branch_description" Type="System.String" DbType="VarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="Update_Date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Create_By" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
    </Type>
  </Table>
</Database>